### ISSUE TITLE
Add docstrings to functions missing docstrings

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#10]
This makes using something like sphinx autodocs easier and using ides like python to create bots a lot faster.

**Comment by percygautam** [comment]
Hi, I'll take this on.

**Comment by TAG-Epic** [comment]
Sounds good! Assigned you to the issue!

**Comment by percygautam** [comment]
Hey @TAG-Epic , exactly which functions need docstrings?

**Comment by TAG-Epic** [comment]
@percygautam all of them really

**Comment by NinoDoko** [comment]
Can others join in too? This also looks like a fun project to do future contributions too!

**Comment by TAG-Epic** [comment]
Yes! Let me assign you.
