### ISSUE TITLE
values.py doesn't have a newline at the end

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#12]
At the moment the version updater removes the newline at the end of the file, making style checks fail.

**Comment by percygautam** [comment]
Hi, I'll take this on.

**Comment by TAG-Epic** [comment]
Sounds good! Assigned you to the issue!

**Comment by percygautam** [comment]
```
for line in lines:
    if line.startswith("version = "):
        version_text = line[len("version = "):]
        old_version = eval(version_text)
        old_version_splitted = old_version.split(".")
        version_tuple = [int(i) for i in old_version_splitted]
        if is_major:
            version_tuple[1] += 1
        else:
            version_tuple[2] += 1
        new_version = f"version = \"{'.'.join([str(i) for i in version_tuple])}\""
        new_lines.append(new_version)
        new_lines.append("\n")
    else:
        new_lines.append(line)
```
This will handle the new line everytime after updating version info, provided version is there in file in the first place (which I think will be the case).
Should I go with PR.

**Comment by TAG-Epic** [comment]
This only adds a newline after `version = "<version number thingy>"`. The version string may not be at the end of the file always. Maybe add a newline after the for loop?

**Comment by percygautam** [comment]
Okay, just to understand things here, the file `update_version.py` script run through all the files in code base and then updates the version wherever it comes across?
But ain't we explicitly defining the `version_file = Path("speedcord/values.py")` in the beginning?

**Comment by TAG-Epic** [comment]
That variable should probably be renamed to be better yeah. I might add a few other values there later. Anyway to make it future proof adding it just after version is bad.

**Comment by percygautam** [comment]
Okay, that was confusing me. Will add after loop.
