### ISSUE TITLE
Rewrite readme

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#18]
Generally having a clearer readme would benefit the project.

**Comment by akshitkumar450** [comment]
i would like to work..please assign this to me.

**Comment by TAG-Epic** [comment]
Okay!

**Comment by geeks5551** [comment]
hey can i do the work? please assign me to it

**Comment by TAG-Epic** [comment]
Sure, one of you do it.

**Comment by MM-coder** [comment]
Created a Pull Request

**Comment by TAG-Epic** [comment]
Solved in #21
