### ISSUE TITLE
Change close code log to info from warning 

### ISSUE THREAD

**Issue by Lost1419** [TAG-Epic/speedcord#27]
# Remove Logs
 Even after taking away ```
basicConfig(level=DEBUG)  # Comment this out if you don't want to see what's going on behind the scenes```
You will still get logs in console. Most of them are `Unknown close code received. Close code: None.`

**Comment by TAG-Epic** [comment]
These are warnings which shows anyway. Might change these in the library to info.
How to disable them for now
```py
from logging import basicConfig, ERROR, getLogger
basicConfig()
getLogger("speedcord.shard").setLevel(ERROR)
```

**Comment by Lost1419** [comment]
Okay thank

**Comment by TAG-Epic** [comment]
Reworked the code, shouldn't log a warning anymore.
