### ISSUE TITLE
Make setup.py not include garbage files 

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#5]
There's a lot of unused files in the output build which increases the size of the library.

Files which should be included
setup.py
speedcord/*
README.md

**Comment by aitorres** [comment]
Hello! I've submitted a quick PR for this issue. If there's anything else I could do or fix from it, let me know!

**Comment by TAG-Epic** [comment]
Fixed in [this commit](https://github.com/TAG-Epic/speedcord/commit/3d1ec752a5a5be9ccf10c9838d892759a518632e)
