### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by TAG-Epic** [TAG-Epic/speedcord#9]
It would be really nice if we could have some documentation with sphinx autodocs. Lets start small and just create a API reference.

**Comment by UdokaVrede** [comment]
Hi can I take this up

**Comment by TAG-Epic** [comment]
Great! Assigned you

**Comment by TAG-Epic** [comment]
Any progress on this?

**Comment by UdokaVrede** [comment]
getting familiar with working with sphinx my first try, it might take time
but If you want to reassign the issue that won't be a problem.

**Comment by TAG-Epic** [comment]
Sounds good! I look forward to see what you can do!

**Comment by MM-coder** [comment]
Maybe use [mkdocs](https://www.mkdocs.org/) with the [material theme](https://squidfunk.github.io/mkdocs-material/)? Sphinx tends to be a pain in the ass.

**Comment by UdokaVrede** [comment]
Hi @TAG-Epic I would pause working on this for now, I got a commitment that would take time. My apologies for this.

**Comment by TAG-Epic** [comment]
Understandable

**Comment by TAG-Epic** [comment]
@MM-coder want to work on it instead?

**Comment by MM-coder** [comment]
MKdocs isn't automatic

**Comment by TAG-Epic** [comment]
Want to do it in sphinx then?

**Comment by shivaco** [comment]
Ready to take over if it can be done in Sphinx.

**Comment by TAG-Epic** [comment]
Sure :)

**Comment by shivaco** [comment]
On it.

**Comment by TAG-Epic** [comment]
Has been merged.
